---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seismic
  namespace: posenet
  labels:
    app: seismic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seismic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: seismic
    spec:
      containers:
        - name: seismic
          image: "gitlab-registry.nrp-nautilus.io/OliverEvans96/seismic:$CI_COMMIT_SHORT_SHA"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
            - containerPort: 3883
          resources:
            limits:
              memory: 1Gi
              cpu: "1"
            requests:
              memory: 1Gi
              cpu: "1"
