---
apiVersion: v1
kind: Service
metadata:
  name: seismic-tcp
  namespace: posenet
  labels:
    app: seismic
  annotations:
    metallb.universe.tf/allow-shared-ip: "seismic"
spec:
  ports:
    - name: data
      port: 7225
      targetPort: 7225
      protocol: TCP
    - name: control
      port: 7224
      targetPort: 7224
      protocol: TCP
  type: LoadBalancer
  selector:
    app: seismic
