---
apiVersion: v1
kind: Service
metadata:
  name: seismic-tcp
  namespace: posenet
  labels:
    app: seismic
  annotations:
    metallb.universe.tf/allow-shared-ip: "seismic"
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
    - name: vrpn
      port: 3883
      targetPort: 3883
      protocol: TCP
  type: LoadBalancer
#  loadBalancerIP: 67.58.49.50
  selector:
    app: seismic
